### ISSUE TITLE
Move this repository to kiedtl/

### ISSUE THREAD

**Issue by kiedtl** [kiedtl/winfetch#81]
I created the `lptstr` repository a few years ago to store my "serious" projects. The idea was to have a place where I could keep side projects I intended for broader use, and keep other things (dotfiles, random scripts, experiments) in my user profile.

However, it's become a bit tedious to follow this pattern and this rule hasn't held true for a while. There are plenty of half-assed junk projects in `lptstr` and a few "serious" projects in `kiedtl`, so I've decided to move everything from `lptstr` to `kiedtl` and just get rid of that pseudo-organization.

Of course, this will be easy to do for things like [chmap](https://github.com/lptstr/chmap), but not so easy for Winfetch, as the repository names are baked into a lot of places. I'm making a list of these places; once I believe I've gotten everything down, I'll transfer the repository and change all the URL references.

List of things to be changed/done before move:

- [x] [README](https://github.com/lptstr/winfetch/blob/9050d9fd4632298e5a38ef8ae2e4bd3a1216a0f1/README.md#L5)
- [x] Choose new name for PowerShell Gallery package
- [x] `winfetch.ps1` [metadata](https://github.com/lptstr/winfetch/blob/master/winfetch.ps1#L7)

After:
- [x] v2.1.0 release
- [x] Chocolatey package
- [x] Scoop package
- [ ] PSGallery Package
- [x] wiki

@jcwillox @rashil2000  Let me know if the repository transfer will affect anything else. Of course, all maintainers will continue to have access after the transfer.

**Comment by rashil2000** [comment]
As long as all the issues, history, redirects from the old URL (for git remote/upstream stuff) get transferred properly I think we would be fine. Github should automatically handle all of that as far as I'm aware.

However I have one doubt, the (long proposed) yet to be published package in the PowerShell Gallery was supposed to be named lptstr-winfetch. Will we be changing this, as a result of the transfer?

**Comment by kiedtl** [comment]
Uhg, that's a rough side. `winfetch` was taken IIRC... I guess we could go along with `kiedtl-winfetch`? or `pwsh-winfetch`?

**Comment by jcwillox** [comment]
Sounds like it should be fine, we should also let the chocolatey thread know (#38), as @jakublevy is maintaining a package for that. There are also some references to the URL in the `winfetch.ps1` file.

**Comment by jakublevy** [comment]
I will push URL changes to chocolatey with the next version.

**Comment by rashil2000** [comment]
We can probably release 3.0 after the shift (couple of new stuff - weather info, native image printing etc.)

**Comment by jcwillox** [comment]
Agreed, I've had a look over at the codebase and everything looks good, we'll wait for the move and then create a new release, which should really be v2.1.0, as it's not a major overhaul. Also when we update the scoop manifest this would also be a good time to address #77.

**Comment by kiedtl** [comment]
We'll use `pwsh-winfetch` for the PowerShell gallery package.

**Comment by kiedtl** [comment]
lukesampson/scoop-extras#6318

**Comment by kiedtl** [comment]
The v2.1.0 release can be done now, after which the Choco and wiki updates can be done.

**Comment by kiedtl** [comment]
@rashil2000 Can we do the release now? The Scoop maintainers seem to be on vacation. ;^))

**Comment by jcwillox** [comment]
Sure, I've already done the release notes, pretty sure I mentioned everything, was just waiting for them to merge the PR first, but you're right there's no point in waiting any longer. You may want to update the PR to point to the new release once we create it.

**Comment by rashil2000** [comment]
Looks good, all green from me!

**Comment by jcwillox** [comment]
Done [v2.1.0](https://github.com/kiedtl/winfetch/releases/tag/v2.1.0) released 🎉

**Comment by jakublevy** [comment]
Chocolatey package updated.
https://community.chocolatey.org/packages/winfetch/2.1.0

**Comment by rashil2000** [comment]
@jcwillox The script metadata is out of date (still shows v2.0.0)

Is there a way to correct it in the 2.1.0 tag branch itself? The updated metadata is necessary for publishing _pwshfetch-test-1_ to PSGallery.

@jakublevy I think you'll need to update the file checksum once this change is made.

**Comment by jakublevy** [comment]
Oh, I didn't inspect the actual file, @rashil2000, you're right, thanks.
I will re-push with an updated checksum.

**Comment by jcwillox** [comment]
Haha we totally missed that, I'm not aware of any way to update the tag, especially without breaking things, we're probably best just creating `v2.1.1`

**Comment by rashil2000** [comment]
It is generally not a good idea to update tags, but I don't think we have any infra in place that would break if we just do it. Correct me if I'm wrong.

**Comment by jcwillox** [comment]
The scoop manifest won't update and it'll have the wrong hash, honestly just safer to create a patch release (which is basically what that stackoverflow answer says)

**Comment by rashil2000** [comment]
This issue can be closed - the only item left was the PSGallery package. It is being tracked in #13
